image: node

cache:
  paths:
    - node_modules

compile:
  stage: build
  script:
    - npm install
    - node build.js
    - cd dist
    - find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD -T {} $FTP_SERVER/{} \;
    - ls -laR